return {
  "EdenEast/nightfox.nvim",
  priority = 1000,
  config = function()
    require("nightfox").setup({
      options = {
        compile_path = vim.fn.stdpath("cache") .. "/nightfox",
        compile_file_suffix = "_compiled", -- Compiled file suffix
        transparent = true, -- Disable setting background
        terminal_colors = true, -- Set terminal colors (vim.g.terminal_color_*) used in `:terminal`
      },
      palettes = {
        nightfox = {
          blue = "#a3bcff",
          red = "#ff3bca",
          green = "#af87df",
          orange = "#eb8098",
          yellow = "#ffc8f8",
        },
      },
      specs = {},
      groups = {
        all = {
          Whitespace = { fg = "#ffffff" },
          -- Normal = { fg = "#ffffff" },
          -- Terminal = { fg = "#ffffff" },
          -- Comment = { fg = "#ff87df" },
          -- PreProc = { fg = "#afafff" },
          -- Type = { fg = "#ffdfff" },
          -- Constant = { fg = "#ffdfff" },
          -- Statement = { fg = "#afd7ff" },
          -- Special = { fg = "#af87df" },
          -- String = { fg = "#af87df" },
          -- cCppString = { fg = "#af87df" },
          -- Number = { fg = "#87d7ff" },
          -- Todo = { fg = "#ff87df", bg = "#875fd7" },
          -- Operator = { fg = "#ffdfdf" },
          -- Float = { fg = "#87d7ff" },
          -- VertSplit = { fg = "#444444", bg = "#444444" },
          -- Wildmenu = { fg = "#ffffff", bg = "#8787ff" },
          -- LineNr = { fg = "#dfafdf" },
          -- Cursor = { bg = "#666666" },
          -- CursorLineNr = { fg = "#8787df" },
          -- ColorColumn = { fg = "#ffdfff" },
          -- NonText = { fg = "#b2b2b2" },
          -- Pmenu = { fg = "#ffdfff", bg = "#666666" },
          -- PmenuSel = { fg = "#afd7ff", bg = "#666666" },
          -- Visual = { bg = "#808080" },
          -- Tag = { fg = "#ff87df" },
          -- Title = { fg = "#ff87df" },
          -- Boolean = { fg = "#afafff" },
          MatchParen = { bg = "#ff87df" },
          -- StorangeClass = { fg = "#ffdfff" },
          -- Function = { fg = "#ffdfff" },
          -- Quote = { fg = "#ff5fff" },
          -- Folded = { fg = "#ff87df", bg = "#666666" },
          -- FoldColumn = { fg = "#ff87df" },
          -- SignColumn = { fg = "#ff87df" },
          -- Directory = { fg = "#ff87df" },
          -- Identifier = { fg = "#afd7ff" },
          -- SpecialKey = { fg = "#afd7ff" },
          -- StatusLine = { fg = "#df87ff", bg = "#444444" },
          -- StatusLineNC = { fg = "#dfafff", bg = "#444444" },
          -- StatusLineTerm = { fg = "#df87ff", bg = "#444444" },
          -- StatusLineTermNC = { fg = "#dfafff", bg = "#444444" },
          -- Character = { fg = "#af87df" },
          -- ErrorMsg = { fg = "#87afdf" },
          -- WaringMsg = { fg = "#87afff" },
          -- ModeMsg = { fg = "#ffffff", bg = "#8787ff" },
          -- MoreMsg = { fg = "#ffffff", bg = "#8787df" },
          -- Question = { fg = "#8700ff" },
          -- Error = { fg = "#e4e4e4", bg = "#d70087" },
          -- Search = { fg = "#ff87df", bg = "#875fd7" },
          -- DiffAdd = { fg = "#ffffff", bg = "#008700" },
          -- DiffChange = { fg = "#ffffff", bg = "#dfaf00" },
          -- DiffDelete = { fg = "#ffffff", bg = "#df0000" },
          -- DiffText = { fg = "#ffffff", bg = "#ff87df" },
        },
      },
    })

    vim.cmd.colorscheme("nightfox")
  end,
}
